version: 1.0.{build}-{branch}

cache:
  - vendor/bundle

environment:
  matrix:
    - RUBY_VERSION: 23
    - RUBY_VERSION: 22
    - RUBY_VERSION: 21
    - RUBY_VERSION: 200

platform:
  - x64
  - x86

install:
  - set _platform=-%Platform%
  - set PATH=C:\Ruby%RUBY_VERSION%%_platform:-x86=%\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake preload
  - bundle exec rake

after_test:
  - bundle exec rake build
  - 7z a root.zip .\pem\*

artifacts:
  - path: root.zip
    name: Root certificates
    type: zip
  - path: pkg/*.gem
    name: Gem
